// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SuperHeroApp.Data;

#nullable disable

namespace SuperHeroApp.Migrations
{
    [DbContext(typeof(SuperHeroAppContext))]
    partial class SuperHeroAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("parafusoInteligente.Infra.Entities.HeroesSuperPowerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IdHeroes")
                        .HasColumnType("integer")
                        .HasColumnName("ID_HEROES");

                    b.Property<int>("IdSuperPower")
                        .HasColumnType("integer")
                        .HasColumnName("ID_SUPER_POWER");

                    b.HasKey("Id");

                    b.HasIndex("IdHeroes");

                    b.HasIndex("IdSuperPower");

                    b.ToTable("T_SUPER_POWER_HEROES");
                });

            modelBuilder.Entity("SuperHeroApp.Models.HeroesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("BIRTH_DATE");

                    b.Property<string>("HeroHeight")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("HERO_HEIGHT");

                    b.Property<string>("HeroName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("HERO_NAME");

                    b.Property<string>("HeroWeight")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("HERO_WEIGHT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.ToTable("T_HEROES");
                });

            modelBuilder.Entity("SuperHeroApp.Models.SuperPowersEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("SuperPower")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("SUPER_POWER");

                    b.HasKey("Id");

                    b.ToTable("T_SUPER_POWER");
                });

            modelBuilder.Entity("parafusoInteligente.Infra.Entities.HeroesSuperPowerEntity", b =>
                {
                    b.HasOne("SuperHeroApp.Models.HeroesEntity", "Heroes")
                        .WithMany("HeroesSuperPower")
                        .HasForeignKey("IdHeroes")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuperHeroApp.Models.SuperPowersEntity", "SuperPowers")
                        .WithMany("HeroesSuperPower")
                        .HasForeignKey("IdSuperPower")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Heroes");

                    b.Navigation("SuperPowers");
                });

            modelBuilder.Entity("SuperHeroApp.Models.HeroesEntity", b =>
                {
                    b.Navigation("HeroesSuperPower");
                });

            modelBuilder.Entity("SuperHeroApp.Models.SuperPowersEntity", b =>
                {
                    b.Navigation("HeroesSuperPower");
                });
#pragma warning restore 612, 618
        }
    }
}
